package com.alireza.testapp.domain.enumeration;

/**
 * The State enumeration.
 */
public enum State {
    ALBORZ, ARDABIL, AZERBAIJAN_EAST, AZERBAIJAN_WEST, BUSHEHR, CHAHAR_MAHAAL_AND_BAKHTIARI, FARS, GILAN, GOLESTAN, HAMADAN, HORMOZGAN, ILAM, ISFAHAN, KERMAN, KERMANSHAH, KHORASAN_NORTH, KHORASAN_RAZAVI, KHORASAN_SOUTH, KHUZESTAN, KOHGILUYEH_AND_BOYER_AHMAD, KURDISTAN, LORESTAN, MARKAZI, MAZANDARAN, QAZVIN, QOM, SEMNAN, SISTAN_AND_BALUCHESTAN, TEHRAN, YAZD, ZANJAN
}
